"use client";

import { useEffect, useState } from "react";
import { HeroSection } from "@/components/hero-section";
import XpBar from "@/components/xpbar";
import QuizTab from "@/components/quiz-tab";
import MovingTimeSeries from "@/components/moving-timeseries";


export default function Home() {
  const [currentXP, setCurrentXP] = useState(2); // Manage XP state here
  const maxXP = 10;

  const question = "What is the most popular video game?";
  const answers = ["Roblox", "Minecraft", "GTA V", "Fortnite"];
  const correctAnswerIndex = 1;

  const handleCorrectAnswer = () => {
    setCurrentXP((prevXP) => Math.min(prevXP + 1, maxXP));
  };

  return (
    <>
      <HeroSection />      
      <XpBar currentXP={currentXP} maxXP={maxXP} />
      <QuizTab
        question={question}
        answers={answers}
        correctAnswerIndex={correctAnswerIndex}
        onCorrectAnswer={handleCorrectAnswer}
      />
      <MovingTimeSeries
        visualizationId="20659797"
        title="Views Generated by Popular Video Games"
      />
      <MovingTimeSeries
        visualizationId="20720610"
        title="Distribution of uploaded videos"
      />


    </>
  );
}
